// SPDX-License-Identifier: Apache-2.0
import type{DatabaseSync}from'node:sqlite';import{stableId}from'@tokentreehq/database';
function now():string{return new Date().toISOString();}
export function ensureSessionAttribution(db:DatabaseSync,sessionId:string):number{
 const session=db.prepare('SELECT project_id,cwd FROM sessions WHERE id=?').get(sessionId) as {project_id:string|null;cwd:string|null}|undefined;if(!session)return 0;let projectId=session.project_id;
 if(!projectId){projectId=stableId('prj','personal-unassigned');const at=now();db.prepare("INSERT OR IGNORE INTO projects(id,key,display_name,identity_hash,detection_method,confidence,created_at,updated_at) VALUES(?,'personal-unassigned','Personal Unassigned',?,'personal_inbox',0.4,?,?)").run(projectId,stableId('identity','personal-unassigned'),at,at);db.prepare('UPDATE sessions SET project_id=? WHERE id=?').run(projectId,sessionId);}
 const workId=stableId('wi',`${projectId}:uncategorized`),at=now();db.prepare("INSERT OR IGNORE INTO work_items(id,project_id,type,title,status,confidence,classifier_version,created_at) VALUES(?,?,'inbox','Uncategorized','open',0,'pending',?)").run(workId,projectId,at);
 const events=db.prepare('SELECT id,input_tokens,cached_input_tokens,cache_write_tokens,output_tokens,reasoning_tokens FROM usage_events WHERE session_id=?').all(sessionId) as Array<Record<string,number|string|null>>;let created=0;
 for(const event of events){const eventId=String(event.id),spanId=stableId('span',eventId),existing=db.prepare('SELECT id FROM usage_spans WHERE id=?').get(spanId);if(existing)continue;const measured=['input_tokens','cached_input_tokens','cache_write_tokens','output_tokens','reasoning_tokens'].some((key)=>typeof event[key]==='number');db.prepare('INSERT INTO usage_spans(id,session_id,measurement_status,measured_usage_json,completeness) VALUES(?,?,?,?,?)').run(spanId,sessionId,measured?'measured':'unavailable',JSON.stringify({usage_event_id:eventId}),measured?100:0);const groupId=stableId('attr',`${spanId}:initial`);db.prepare("INSERT INTO attribution_groups(id,usage_span_id,policy,active,created_at) VALUES(?,?,'causal-request',1,?)").run(groupId,spanId,at);db.prepare("INSERT INTO attributions(group_id,project_id,work_item_id,role,weight_basis_points,method,confidence,verified_by_user) VALUES(?,?,?,'primary',10000,'session_default',0,0)").run(groupId,projectId,workId);created++;}
 return created;
}
export function attachSession(db:DatabaseSync,sessionId:string,workItemId:string):number{const target=db.prepare('SELECT project_id FROM work_items WHERE id=?').get(workItemId) as {project_id:string}|undefined;if(!target)throw new Error(`Unknown work item ${workItemId}`);ensureSessionAttribution(db,sessionId);const events=db.prepare('SELECT id FROM usage_events WHERE session_id=?').all(sessionId) as Array<{id:string}>;let changed=0;db.exec('BEGIN IMMEDIATE');try{for(const event of events){const spanId=stableId('span',event.id),active=db.prepare('SELECT id FROM attribution_groups WHERE usage_span_id=? AND active=1').get(spanId) as {id:string}|undefined;if(active)db.prepare('UPDATE attribution_groups SET active=0 WHERE id=?').run(active.id);const groupId=stableId('attr',`${spanId}:${workItemId}:${Date.now()}`);db.prepare("INSERT INTO attribution_groups(id,usage_span_id,policy,supersedes_group_id,active,created_at) VALUES(?,?,'causal-request',?,1,?)").run(groupId,spanId,active?.id??null,now());db.prepare("INSERT INTO attributions(group_id,project_id,work_item_id,role,weight_basis_points,method,confidence,verified_by_user) VALUES(?,?,?,'primary',10000,'manual_attach',1,1)").run(groupId,target.project_id,workItemId);changed++;}db.prepare('UPDATE sessions SET project_id=? WHERE id=?').run(target.project_id,sessionId);db.exec('COMMIT');}catch(error){db.exec('ROLLBACK');throw error;}return changed;}
export function detachSession(db:DatabaseSync,sessionId:string):number{const spans=db.prepare('SELECT id FROM usage_spans WHERE session_id=?').all(sessionId) as Array<{id:string}>;let changed=0;db.exec('BEGIN IMMEDIATE');try{for(const span of spans){changed+=Number(db.prepare('UPDATE attribution_groups SET active=0 WHERE usage_span_id=? AND active=1').run(span.id).changes);}db.prepare('UPDATE sessions SET project_id=NULL WHERE id=?').run(sessionId);db.exec('COMMIT');}catch(error){db.exec('ROLLBACK');throw error;}return changed;}
export function addNote(db:DatabaseSync,text:string,workItemId?:string):string{if(text.length<1||text.length>240)throw new Error('Notes must be 1–240 characters');let target=workItemId;if(!target){const run=db.prepare("SELECT work_item_id FROM manual_runs WHERE state='active' ORDER BY started_at DESC LIMIT 1").get() as {work_item_id:string}|undefined;target=run?.work_item_id;}if(!target)throw new Error('Specify a work item or start a manual run');const row=db.prepare('SELECT project_id FROM work_items WHERE id=?').get(target) as {project_id:string}|undefined;if(!row)throw new Error(`Unknown work item ${target}`);const id=stableId('note',`${target}:${Date.now()}:${text}`);db.prepare("INSERT INTO notes(id,project_id,work_item_id,text,created_by,created_at) VALUES(?,?,?,?, 'user',?)").run(id,row.project_id,target,text,now());return id;}
