// SPDX-License-Identifier: Apache-2.0
import type{DatabaseSync}from'node:sqlite';import{calculateApiEquivalentCost,loadPriceSnapshot,resolveSnapshotRate}from'@tokentreehq/pricing';import{stableId}from'@tokentreehq/database';
export interface PricingSummary{readonly priced:number;readonly unavailable:number;readonly alreadyCalculated:number;}
export function applyPriceSnapshot(db:DatabaseSync,path:string):PricingSummary{
 const snapshot=loadPriceSnapshot(path);let priced=0,unavailable=0,alreadyCalculated=0;
 const events=db.prepare('SELECT id,model,source_timestamp,observed_at,input_tokens,cached_input_tokens,cache_write_tokens,output_tokens,reasoning_tokens FROM usage_events').all() as Array<Record<string,string|number|null>>;
 db.exec('BEGIN IMMEDIATE');try{for(const event of events){const model=typeof event.model==='string'?event.model:null,rate=model?resolveSnapshotRate(snapshot,model,new Date(String(event.source_timestamp??event.observed_at))):null;if(!rate){unavailable++;continue;}const priceId=stableId('price',`${rate.provider}:${rate.modelPattern}:${rate.effectiveFrom}:${snapshot.sha256}`);db.prepare('INSERT OR IGNORE INTO pricing_versions(id,provider,model_pattern,effective_from,rates_json,source,retrieved_at,signature_or_hash) VALUES(?,?,?,?,?,?,?,?)').run(priceId,rate.provider,rate.modelPattern,rate.effectiveFrom,JSON.stringify(rate),rate.source,snapshot.updated,snapshot.sha256);const cost=calculateApiEquivalentCost({inputTokens:numberOrNull(event.input_tokens),cachedInputTokens:numberOrNull(event.cached_input_tokens),cacheWriteTokens:numberOrNull(event.cache_write_tokens),outputTokens:numberOrNull(event.output_tokens),reasoningTokens:numberOrNull(event.reasoning_tokens)},rate);if(cost.amountMicros===null){unavailable++;continue;}if(cost.amountMicros>BigInt(Number.MAX_SAFE_INTEGER))throw new Error('Calculated cost exceeds SQLite safe integer range');const info=db.prepare("INSERT OR IGNORE INTO cost_calculations(usage_event_id,pricing_version_id,amount_micros,currency,cost_type,attribution_policy,coverage_json,calculated_at) VALUES(?,?,?,'USD','api_equivalent_estimate','causal-request',?,?)").run(String(event.id),priceId,Number(cost.amountMicros),JSON.stringify({model:true,cache:cost.missingCategories.length===0,source:snapshot.sha256}),new Date().toISOString());if(info.changes)priced++;else alreadyCalculated++;}db.exec('COMMIT');}catch(error){db.exec('ROLLBACK');throw error;}return{priced,unavailable,alreadyCalculated};
}
function numberOrNull(value:string|number|null|undefined):number|null{return typeof value==='number'?value:null;}
